[package]
name = "webServer"
version = "0.1.0"
authors = ["aiuzunov <aleksandar.i.uzunov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
