export const EMPLOYEE_SIGNIN_REQUEST = 'EMPLOYEE_SIGNIN_REQUEST';
export const EMPLOYEE_SIGNIN_SUCCESS = 'EMPLOYEE_SIGNIN_SUCCESS';
export const EMPLOYEE_SIGNIN_FAIL = 'EMPLOYEE_SIGNIN_FAIL';

export const EMPLOYEE_SIGNUP_REQUEST = 'EMPLOYEE_SIGNUP_REQUEST';
export const EMPLOYEE_SIGNUP_SUCCESS = 'EMPLOYEE_SIGNUP_SUCCESS';
export const EMPLOYEE_SIGNUP_FAIL = 'EMPLOYEE_SIGNUP_FAIL';
