export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';


export const ADDRESS_SAVE_REQUEST = 'ADDRESS_SAVE_REQUEST';
export const ADDRESS_SAVE_SUCCESS = 'ADDRESS_SAVE_SUCCESS';
export const ADDRESS_SAVE_FAIL = 'ADDRESS_SAVE_FAIL';

export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL';