export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CARTITEM_SAVE_REQUEST = 'CARTITEM_SAVE_REQUEST';
export const CARTITEM_SAVE_SUCCESS = 'CARTITEM_SAVE_SUCCESS';
export const CARTITEM_SAVE_FAIL = 'CARTITEM_SAVE_FAIL';


export const CARTITEM_DELETE_REQUEST = 'CARTITEM_DELETE_REQUEST';
export const CARTITEM_DELETE_SUCCESS = 'CARTITEM_DELETE_SUCCESS';
export const CARTITEM_DELETE_FAIL = 'CARTITEM_DELETE_FAIL';
