export const EMPLOYEE_SIGNIN_REQUEST = 'EMPLOYEE_SIGNIN_REQUEST';
export const EMPLOYEE_SIGNIN_SUCCESS = 'EMPLOYEE_SIGNIN_SUCCESS';
export const EMPLOYEE_SIGNIN_FAIL = 'EMPLOYEE_SIGNIN_FAIL';

export const EMPLOYEE_SIGNUP_REQUEST = 'EMPLOYEE_SIGNUP_REQUEST';
export const EMPLOYEE_SIGNUP_SUCCESS = 'EMPLOYEE_SIGNUP_SUCCESS';
export const EMPLOYEE_SIGNUP_FAIL = 'EMPLOYEE_SIGNUP_FAIL';

export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST';
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS';
export const EMPLOYEE_LIST_FAIL = 'EMPLOYEE_LIST_FAIL';

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL';
