export const INCOMES_LIST_REQUEST = 'INCOMES_LIST_REQUEST';
export const INCOMES_LIST_SUCCESS = 'INCOMES_LIST_SUCCESS';
export const INCOMES_LIST_FAIL = 'INCOMES_LIST_FAIL';

export const SOLDPRODUCTS_LIST_REQUEST = 'SOLDPRODUCTS_LIST_REQUEST';
export const SOLDPRODUCTS_LIST_SUCCESS = 'SOLDPRODUCTS_LIST_SUCCESS';
export const SOLDPRODUCTS_LIST_FAIL = 'SOLDPRODUCTS_LIST_FAIL';

export const REGUSERS_LIST_REQUEST = 'REGUSERS_LIST_REQUEST';
export const REGUSERS_LIST_SUCCESS = 'REGUSERS_LIST_SUCCESS';
export const REGUSERS_LIST_FAIL = 'REGUSERS_LIST_FAIL';

export const BESTSELLERS_LIST_REQUEST = 'BESTSELLERS_LIST_REQUEST';
export const BESTSELLERS_LIST_SUCCESS = 'BESTSELLERS_LIST_SUCCESS';
export const BESTSELLERS_LIST_FAIL = 'BESTSELLERS_LIST_FAIL';
