---

indicator: submit
elements:
    - type: Number
      name: user_id
      label: Потребител
      attributes:
        title: Въведете id-то на потребителя тук

    - type: Number
      name: address_id
      label: Адрес
      attributes:
        title: Въведете id-то на адреса тук

    - type: Text
      name: order_status
      label: Статус на поръчката
      attributes:
        title: Въведете статуса на поръчката тук

    - type: Text
      name: phone_number
      label: Телефон за връзка
      attributes:
        title: Въведете телефона за връзка с клиента тук

    - type: Text
      name: buyer_name
      label: Име на получателя
      attributes:
        title: Въведете името на получателя тук

    - type: Number
      name: price
      label: Цена
      attributes:
        title: Въведете общата сума на поръчката тук


    - type: Submit
      name: submit
      value: Добави/Обнови

constraints:
  - Required
filter:
  - TrimEdges
  - HTMLEscape
